### ISSUE TITLE
Build errors attempting Code v1.45.0

### ISSUE THREAD

**Issue by martin-gregory** [dsugiyama/build-vscode-win-arm64#1]
Hi,
I appreciate that this is an un conventional approach to contact you but I have been using your arm64 build of VS Code for months and it's wonderful. However there are new versions of code released often.

So I have been trying to compile the latest version using the steps you have outlined here. I have got a build that runs on win arm64 but there appear to be problems. I was hoping that you may have encountered them before and could be able to point me to some solutions.

Looking in the developer tools there are a number of errors relating to 
"resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node is not a valid Win32 application"
I have attempted a few different versions of node, sqlite etc and so far I cannot get it to work but perhaps you have an insight.

Either way I'm sure you're very busy and I thank you for your efforts.
Martin

**Comment by dsugiyama** [comment]
> "resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node is not a valid Win32 application"

I'm not sure but maybe sqlite is not built correctly as an ARM64 binary. Can you try `set npm_config_target_arch=arm64` in addition to `set npm_config_arch=arm64`? I'll also try building the latest vscode in my env with and without `set npm_config_target_arch=arm64` and see what happens.

Also, as you might already know, the latest vscode has Win/ARM64 build support in mainline (microsoft/vscode#85326). So you don't need to patch to build it. I'll update the instruction if I have a time.

**Comment by martin-gregory** [comment]
Finally got it to work, you were right!
I wasn't passing the node env arch=arm64 correctly because I'm using powershell and you cannot set the variables in the same way. I also fell into the deep hole of node-gyp & MSBuild issues. 
Yes it's encouraging that you don't need to patch for arm64 support. Let's hope they support it officially.
Anyway I'll be compiling this quite often as I use it as my primary dev platform, I'm happy to post a build up each time. Thanks for the help

**Comment by dsugiyama** [comment]
I'm glad it worked out for you!
